image: node:6

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn global add parcel-bundler --ignore-engines
  - yarn install
  - yarn build --out-dir public

  artifacts:
    paths:
    - public

  only:
    - master
